id: P558484AE
initial_creation_type: input
source_metadata:
  title: 'Nāgārjuna: Mūlamadhyamakakārikā'
  language: zh
  volumes:
    99fc9636ad594686b8865dc44f598f2e:
      title: 'CIII_Chapter XI: Pūrvāparakoṭiparīkṣa'
      base_file: 'CIII_Chapter XI: Pūrvāparakoṭiparīkṣa.txt'
      work_id: W8CF652EA
    06dff2d6a26e401ea50c2674d27823fe:
      title: 'CIII_Chapter XII: Duḥkhaparīkṣā'
      base_file: 'CIII_Chapter XII: Duḥkhaparīkṣā.txt'
      work_id: W442244D2
    c3daaa35b4f449d69045a5b7eb62b252:
      title: 'CIII_Chapter XIII: Saṃskāraparīkṣā'
      base_file: 'CIII_Chapter XIII: Saṃskāraparīkṣā.txt'
      work_id: W63343241
    679106bae72d450b93ea0919c78dc352:
      title: 'CIII_Chapter XIV: Saṃsargaparīkṣā'
      base_file: 'CIII_Chapter XIV: Saṃsargaparīkṣā.txt'
      work_id: W9B2D00B2
    98e06dbc0d314b9898fe42e4b019952c:
      title: 'CIII_Chapter XV: Svabhāvaparīkṣā'
      base_file: 'CIII_Chapter XV: Svabhāvaparīkṣā.txt'
      work_id: WC21EB391
    033d829f54a24404a5c0cd483c2a01a4:
      title: 'CII_Chapter IX: Pūrvaparīkṣā'
      base_file: 'CII_Chapter IX: Pūrvaparīkṣā.txt'
      work_id: W0B480717
    6632f49414c64b299a4674c37c09cc0b:
      title: 'CII_Chapter VI: Rāgasaktiparīkṣā'
      base_file: 'CII_Chapter VI: Rāgasaktiparīkṣā.txt'
      work_id: W7B266BBE
    f1141717954c45b1b06590a283d9f2fa:
      title: 'CII_Chapter VII: Saṃskr̥̥taparīkṣā'
      base_file: 'CII_Chapter VII: Saṃskr̥̥taparīkṣā.txt'
      work_id: W8D5E4ECA
    2a56adb1f91943d68925fdc4bca60d6c:
      title: 'CII_Chapter VIII: Karmakārakaparīkṣā'
      base_file: 'CII_Chapter VIII: Karmakārakaparīkṣā.txt'
      work_id: W794544BA
    3777f0101be44253afdedbe8d08db719:
      title: 'CII_Chapter X: Agnīndhanaparīkṣā'
      base_file: 'CII_Chapter X: Agnīndhanaparīkṣā.txt'
      work_id: W5845B4A6
    7994fadf77084c249ac2b2ead9061bf2:
      title: 'CIV_Chapter XIX: Kālaparīkṣā'
      base_file: 'CIV_Chapter XIX: Kālaparīkṣā.txt'
      work_id: W71FA611E
    9edf8b31dce94404ad5a90692e112592:
      title: 'CIV_Chapter XVI: Bandhanamokṣaparīkṣā'
      base_file: 'CIV_Chapter XVI: Bandhanamokṣaparīkṣā.txt'
      work_id: WDAF9A99A
    5fa6ae14368e49aaaf28c12a4e138341:
      title: 'CIV_Chapter XVII: Karmaphalaparīkṣā'
      base_file: 'CIV_Chapter XVII: Karmaphalaparīkṣā.txt'
      work_id: W44461A3A
    9bac42bd091447c2884822b92a048b78:
      title: 'CIV_Chapter XVIII: Ātmaparīkṣā'
      base_file: 'CIV_Chapter XVIII: Ātmaparīkṣā.txt'
      work_id: W2B500C35
    31c1610480074f4db82542a1411c2e05:
      title: 'CIV_Chapter XX: Sāmagrīparīkṣā'
      base_file: 'CIV_Chapter XX: Sāmagrīparīkṣā.txt'
      work_id: W0FAAAB6C
    d9a45e32d2624b88bf113478598cd5d2:
      title: 'CI_Chapter I: Pratyayaparīkṣā'
      base_file: 'CI_Chapter I: Pratyayaparīkṣā.txt'
      work_id: W1A21CABA
    ebb768a644a24be6947a93b9d917ca7b:
      title: 'CI_Chapter II: Gatāgataparīkṣaṇa'
      base_file: 'CI_Chapter II: Gatāgataparīkṣaṇa.txt'
      work_id: WD0DD7947
    0d36c2666fd6439abc8bc801ab5a85b1:
      title: 'CI_Chapter III: Cakṣurādīndriyaparīkṣā'
      base_file: 'CI_Chapter III: Cakṣurādīndriyaparīkṣā.txt'
      work_id: W51FF509B
    ebc474472868446aa49e3f712614b9f3:
      title: 'CI_Chapter IV: Skandhaparīkṣā'
      base_file: 'CI_Chapter IV: Skandhaparīkṣā.txt'
      work_id: W755F7587
    40a56472717242dfb4715666bfe8475a:
      title: 'CI_Chapter V: Dhātuparīkṣā'
      base_file: 'CI_Chapter V: Dhātuparīkṣā.txt'
      work_id: W9CFEFF50
    1d39427db49349278fc7d88b9bb61e73:
      title: 'CVI_Chapter XXVI: Dvādaśāṅgaparīkṣā'
      base_file: 'CVI_Chapter XXVI: Dvādaśāṅgaparīkṣā.txt'
      work_id: W7817019A
    37d42f92f68344eea3ace84fd1f84b3a:
      title: 'CVI_Chapter XXVII: Dr̥ṣṭiparīkṣā'
      base_file: 'CVI_Chapter XXVII: Dr̥ṣṭiparīkṣā.txt'
      work_id: WD6D64747
    686daa487c6b4470adf432c3679f204f:
      title: 'CV_Chapter XXI: Saṃbhavavibhavaparīkṣā'
      base_file: 'CV_Chapter XXI: Saṃbhavavibhavaparīkṣā.txt'
      work_id: W10B0A880
    a6804c6427964159bb4b645120d771cf:
      title: 'CV_Chapter XXII: Tathāgataparīkṣā'
      base_file: 'CV_Chapter XXII: Tathāgataparīkṣā.txt'
      work_id: WB9B3A554
    4b30604b7a30425580fd9e140a5c5a5a:
      title: 'CV_Chapter XXIII: Viparyāsaparīkṣā'
      base_file: 'CV_Chapter XXIII: Viparyāsaparīkṣā.txt'
      work_id: W1AD24770
    447b77a420a04b149f66d5bd3e5820ce:
      title: 'CV_Chapter XXIV: Āryasatyaparīkṣā'
      base_file: 'CV_Chapter XXIV: Āryasatyaparīkṣā.txt'
      work_id: W9C64778F
    615b5acac5004e0e84ece1e0ddcf7bad:
      title: 'CV_Chapter XXV: nirvāṇaparīkṣā'
      base_file: 'CV_Chapter XXV: nirvāṇaparīkṣā.txt'
      work_id: W5FE9CC2E
    1fe8e561f6a74372868d6baab8480cf5:
      title: Colophon
      base_file: Colophon.txt
      work_id: W04130B34
    19cf1e5165c74770b3ac601d97bb531f:
      title: Preface
      base_file: Preface.txt
      work_id: WC444C421
    96a3d0e5e6874a07a24ba34cd9875433:
      title: Title
      base_file: Title.txt
      work_id: W95D96C22
  chapter_to_tile:
    CI: Chapters I-V
    CII: Chapters VI-X
    CIII: Chapters XI-XV
    CIV: Chapters XVI-XX
    CV: Chapters XXI-XXV
    CVI: Chapters XXVI-XXVII
created_at: '2022-03-01T23:08:20.038846'
last_modified_at: '2022-03-01T23:08:20.038857'
